import {
  BadgeCheck,
  Briefcase,
  Building,
  Building2,
  CircleAlert,
  CircleHelp,
  Coffee,
  Compass,
  Ellipsis,
  FileCheck,
  FileSignature,
  FileText,
  Globe,
  Hammer,
  Home,
  House,
  HousePlus,
  KeyRound,
  Landmark,
  RefreshCw,
  Search,
  Stethoscope,
  Sun,
  ThumbsUp,
  TrendingDown,
  UserRound,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const optionIconMap: Record<string, LucideIcon> = {
  house: House,
  refresh: RefreshCw,
  "house-plus": HousePlus,
  "building-2": Building2,
  building: Building,
  hammer: Hammer,
  landmark: Landmark,
  "circle-help": CircleHelp,
  home: Home,
  sun: Sun,
  "key-round": KeyRound,
  compass: Compass,
  search: Search,
  "file-signature": FileSignature,
  briefcase: Briefcase,
  user: UserRound,
  "file-text": FileText,
  stethoscope: Stethoscope,
  "file-check": FileCheck,
  globe: Globe,
  ellipsis: Ellipsis,
  "badge-check": BadgeCheck,
  "thumbs-up": ThumbsUp,
  "circle-alert": CircleAlert,
  "trending-down": TrendingDown,
  coffee: Coffee,
};

export function getOptionIcon(key: string): LucideIcon {
  return optionIconMap[key] ?? CircleHelp;
}
